language: java
install: true
jdk:
  - openjdk11
services:
  - docker
  - redis-server
cache:
  directories:
    - "$HOME/.cache"
env:
  global:
    - secure: mi9rv39PWmIved10b7hRIq7ctD/OxtlFOB8GY1ahS/IuC22OPfsW0gw+5WCinYpo3I+66C89mLOoFWI9y4kwId5o0Bxs5G6GDlpJh7JJLfqL5kGuqanpAOxYv7VB/NVAy6yzG9IUsgaMmB9YeXWyEeJS9EETS78ua1T2kxoJBdxHdIyVtnbSsSk8F5PNOBoy26kK1lHpeFMsa4WIU4rqoE7SnPJOT4JTi0ScvVq9cFji54JulTmhCJMwt3mPKeN48YFxEphix7khoV2XdjquhVMT7EULrV5+mFjumL4/33GXnYiwJQReZnbf5xpMU2EGPiW/jhiSVnjRaOMzN9VOZC17OwM78GYcUKMWyTy4pSQp2Nf7woqVCb6BIgfHoOI0zcP5Qd24t0UUwIfsoKCwZWFhIhS7gc0TaEjXTmw1td1VoQYXCyMrUNTbpqbPw9hlKg62hhR7hslEjZS8Y8tGqct2Xe0CWwH+xiMvsZfHhBPfpkywx0Fs6XL5fUu0K3MtGZmMGdqqE9ak9V52HPPrk4QsFy834qrmGWfNrAigteg2FhOGMCWoAM/lsOCX/Hp0hhZeaYTiHFyAsLOflyw4tZBDZJT1noj8FSl3I2sNq+oJJud1CbvqQ21nwyw2FOLE46QEIYYGwyTVRTJG61f5fZqwQEadan4ICwGYh5d7wTI=
    - secure: c3g5NUY3ZTFckWTANupKR1DAZhzM3J9IZl5bcjxi20h71Ck7NDaaC5oj/6BfPFjy7fAKO9SF0Z2jwRg8U1E2aDKL75WFUR4DrcMMwMiLCzfCx7M2ZND294vsSM7PE3hlmO0zumaqKZ0RtIpzOnEPR7O2VEU/XSEqIJOw8NrpcaQKgLTDzif+vyJXgFj//f5/h8lzAB8WPps/KvM0sd0hod+pwOu64qW+JrRNxa5A9mb6UzSa3VW1ZNdzCb7XVvA4gGS5S9DThGH9k2v+Oh0al7simqwLiMXt4Wy6JhzzqWa3b5rxcmdExbtaCtLvICgCSxD1jIoAGDFKFKAfcb9r2A8dQEBB/1n/CPNQde80WNqhJdx4+n2HzvEsokmAjaq3XeZStpdW0YjzFDmYEN+mJV4K4pp6FrAoBS0QrQ7VXZXB/rAAO1g12Hj2cAQMuwllf+uP30ltb45iV96YgLnq2YqHcseUeL3N30DkoFB4YWSpuhR14XAfM3zYm3opxKE9gU7htw+5DSlAszNlLQ4JZrQyHF4NwVjN4QHtmKF+V1n41o6KVLurxG327/yg7x58TnRVoHPj8HoNgMlbFmReInz1m+WmOVv+dpyqvnXoUgJp/mJ+kK/ywQQvYJYHbYKw9aM9eT+4vtRfyFAqfgg8uXSHzxhtyDMKsebByYi9sEg=
    - secure: Dgj5foWAxoxpc6e60G9X5gPqkEwTB6/yPoMwpI4kid0bZmyBEOUmMdJTYxuY2151+fFlRcGj2EevUKb4FJE49u4wq3P//zyIvifsB96TBxT67lHf/KJWZ511RM79vW67ijv1YE8RHi/dYv1zRudaxWPLAlFIrlqmklHX4POc5P0jthw0bxcTwq4iSNP5p2iPYaaGN3xCgKpYXbwN0xqSvea6EC4RYlGU7tukA3I+zVpF0+xzKb7b25I8wtnpZD7s0ob0ifxZjjxuuWTLaCzF/J9XwmF+9QiqrScq/uVMonAYUBn+eHpPtGZQ8Ht84dEQD8UCebfOqjqnVOBiVYWuT+IG4F/zAghUDUWceYoLykTzOOQ+ZEw0zgpJQ63g8nAYhH9gELapuSfa5pNBOiZSWLm9ZKgmyNKmtKxqoHSvbFNM0VdzxMt9tjaPjkv70/I5SL41EtWKeYH0RusnbEmnW2aijjptb1/FdKkUNsrJ9WjbxfZQUklY/B8KFV1zc0g2oY6LPSJNgwADnQt9hZY9Hdwqx2f4V2p1dPnZv2lkSgJv2abVey/GEwuXfx13GWS/ImTPZI4NSnGVZVHvPxthM8s1WOysaS0SCyBiSHiY77lL+EluWcnwFkTFxvJJzwmaFWcH7dIPdWMeOyXAtbEq4VE0gPYJuGPJPgIJXoqKJvw=
addons:
  hosts:
    - redis-server
  sonarcloud:
    organization: sunxuia
    token:
      secure: cC1IbZlPyeCPmcObi/3h4SZXxVq87RPzkodjoJZ2p9AD3REZKtZ71DUCTBeRNH7ao9BQ8afZyeBYvuVvCWcdOweffWvEOuIqzSX9CPkub0cXvGd0U9BJIYYDU839aPc4QIcc8ulOtqDG80WWXWBTGC94BA3p5EepI46PYC4w5TaRvx9FE2TNL2bhfS6Owjdaa3d1Qyf3psBi4rfxndRnP3t6cM+cdDYms8M9C6F9auGHe/7uzhwPlUCtBkI9KdFX7R8qoTfW0Cq+PLcEKkPw/llWnEFv5V4hdAqRtZR/r9iv/t4Ip3SbQ1v5I3+RAfBPDWxdtxlF1yCQRiqvz+GsKS3eFC5sriZbSy0kZ385k3wKJbN97FedhMLI8a8nW9qrMuavleC87fiabZhhexxxxhFspLWJMJbNkVB8P4tG4w4LiF8fMbdBgxEwkGleAYPhBpR7zpBsPNHFwvpDrnPf0aFZWsK4Vp8Jw2t4gSSQ3Bc9xz9CTnE7xgq1VYELYZa07rPADFI+yWudTbWzc3ptkRzQyePoXQiGU6pHZJUV5qF+d0jcwQU74ud/BzPT1thAe1F24+Dz9h7lCLG9NJaVt4OLix+vG7p/3+WPup8FNuCBQFJxbGZdHNhZlowNEQByBkKVGB87Iseqia4FQl8L/a0smNkaGz3cCZiI86LgvUw=
  apt:
    packages:
      - docker-ce
script:
  - chmod +x build.sh && ./build.sh
  - rm -f ~/.docker/config.json
